### ISSUE TITLE
Callbacks not working in SimpleClient

### ISSUE THREAD

**Issue by palmerc** [jebej/MatlabWebSocket#4]
The callbacks are not correctly registering. Have you seen this issue? I'm running R2016B, JRE 1.8 on macOS 10.12.5.

```
java.lang.NullPointerException
	at com.mathworks.jmi.bean.MatlabBeanInterface.addCallback(MatlabBeanInterface.java:484)
	at com.mathworks.jmi.bean.MatlabCallbackInterface.addCallback(MatlabCallbackInterface.java:130)
java.lang.NullPointerException
	at com.mathworks.jmi.bean.MatlabBeanInterface.addCallback(MatlabBeanInterface.java:484)
	at com.mathworks.jmi.bean.MatlabCallbackInterface.addCallback(MatlabCallbackInterface.java:130)
java.lang.NullPointerException
	at com.mathworks.jmi.bean.MatlabBeanInterface.addCallback(MatlabBeanInterface.java:484)
	at com.mathworks.jmi.bean.MatlabCallbackInterface.addCallback(MatlabCallbackInterface.java:130)
java.lang.NullPointerException
	at com.mathworks.jmi.bean.MatlabBeanInterface.addCallback(MatlabBeanInterface.java:484)
	at com.mathworks.jmi.bean.MatlabCallbackInterface.addCallback(MatlabCallbackInterface.java:130)
```

**Comment by jebej** [comment]
I haven't seen this issue, but are you sure you are on JRE 1.8? I thought MATLAB was still on 1.7. I might be mistaken.

**Comment by palmerc** [comment]
Issue is actually the need to edit classpath.txt vs javaaddpath at runtime.

**Comment by jebej** [comment]
Ok, I'll close the issue as this is documented.
